### ISSUE TITLE
Deserializing Interval discards timezone information

### ISSUE THREAD

**Issue by Woodz** [FasterXML/jackson-datatype-joda#104]
- Version: jackson-datatype-joda v2.9.5
- Dependencies:
  - play-json_2.11-2.4.3
  - joda-time-2.10
- Repro: `play.libs.Json.fromJson(new TextNode("2001-01-01T01:01:01.000+06:00/2001-01-01T01:01:02.000+06:00"), org.joda.time.Interval.class)`
- Expected: `2001-01-01T01:01:01.000+06:00/2001-01-01T01:01:02.000+06:00`
- Actual: `2000-12-31T19:01:01.000Z/2000-12-31T19:01:02.000Z`

**Comment by Xyaren** [comment]
The same Happenes with DateTime....

**Comment by cowtowncoder** [comment]
As per my notes on PR, this would require updating minimum required Joda version to 2.9.
While not unreasonable (2.9 has been out for 4 years now), it needs to go in a new minor version, I think (as a general rule).

I send a note on `jackson-dev` mailing list, asking if anyone knew of potential issues, but assuming none reported, I can and will merge this for 2.11 branch.
