### ISSUE TITLE
`JodaDateSerialize`r Discards Shape Override Preference

### ISSUE THREAD

**Issue by knocknarea** [FasterXML/jackson-datatype-joda#108]
If you create a Serializer (for example LocalTimeSerializer) with a String shape preference, this preference get discarded at this point

https://github.com/FasterXML/jackson-datatype-joda/blob/86189159366013a1fd782112a310eaffb5f70b1c/src/main/java/com/fasterxml/jackson/datatype/joda/ser/JodaDateSerializerBase.java#L89

example

```
class DTO {
   LocalTime timeIn;
}
```

Configure Module
```
module.addSerializer(LocalTime.class, new LocalTimeShapedDeserializer(
	    		new JacksonJodaDateFormat(ISODateTimeFormat.hourMinute()), 1));

```

When the above DTO is serialized, the time is rendered [ hh, mm, sec, ms ] instead of the desired and configured way

The fact that the LocalTime.class serializer has been created to use the string shape (in this instance "hh:mm") gets ignored and in the above code 

```
            } else  {
                useTimestamp = null;
                shapeOverride = 0; // should this not be set to _shapeOverride??
            }
            // must not call if flag defined, to rely on defaults:
            if (useTimestamp != null) {
                format = format.withUseTimestamp(useTimestamp);
            }
            format = format.with(ann);
            if ((format != _format) || (shapeOverride != _shapeOverride)) {
                return withFormat(format, shapeOverride);
            }

```

**Comment by cowtowncoder** [comment]
I would need full code for reproduction: although description helps, there are couple of aspects that are unclear to me, and easiest way is to just show code.
