### ISSUE TITLE
publish 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-datatype-joda#111]
jackson-module-scala has test dependencies on jackson-datatype-joda and the lack of a jackson-datatype-joda 3.0.0-SNAPSHOT is causing issues

https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/datatype/jackson-datatype-joda/

**Comment by cowtowncoder** [comment]
I'll deploy snapshot from home tonight.
