### ISSUE TITLE
DateTimeTest.testCustomPatternStyle fails with Java 21

### ISSUE THREAD

**Issue by vpa1977** [FasterXML/jackson-datatype-joda#132]
Java 21 changed time format due to https://bugs.openjdk.org/browse/JDK-8284840

The following assertion fails 
```
[ERROR]   DateTimeTest.testCustomPatternStyle:136 expected:<..."date":"1/1/70 12:00[ ]AM"}> but was:<..."date":"1/1/70 12:00[ ]AM"}>
```
because 12:00 and AM are now separated by NBSP character.

**Comment by cowtowncoder** [comment]
Thank you @vpa1977 !
