### ISSUE TITLE
Links in the Wiki are broken

### ISSUE THREAD

**Issue by aidin36** [FasterXML/jackson-datatype-joda#136]
The README file points to the Wiki for Javadocs. But the links in the Wiki are broken. Also, newer versions aren't listed.

I couldn't find the Javadocs otherwise I would send a PR.

**Comment by pjfanning** [comment]
try https://javadoc.io/doc/com.fasterxml.jackson.datatype/jackson-datatype-joda/latest/index.html

if you go to https://javadoc.io/ - you can just fill in the groupId and artifactid

**Comment by pjfanning** [comment]
I updated the wiki

**Comment by cowtowncoder** [comment]
Yes, we (I) stopped pushing Javadocs to Github repos due to negative effects they have on repo sizes.

So, `javadoc.io` is the place; main README has a link there (one of badges).
