### ISSUE TITLE
DateTimeSerializer should take the configured time zone into account

### ISSUE THREAD

**Issue by pavax** [FasterXML/jackson-datatype-joda#21]
At the moment the com.fasterxml.jackson.datatype.joda.ser.DateTimeSerializer writes the following code if  the WRITE_DATES_AS_TIMESTAMPS feature is disabled:
...
 jgen.writeString(value.toString());
...
whereas value is the DateTime object. However this doesn't take the configured timezone into account which might be set in ObjectMapper.setTimeZone(TimeZone timeZone).  

A similar Issue was fixed for the DateTimeDeserializer see: https://github.com/FasterXML/jackson-datatype-joda/pull/14

**Comment by Macarse** [comment]
@cowtowncoder This change was not mentioned in https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.3.1

**Comment by cowtowncoder** [comment]
@Macarse thanks, added it there.
