### ISSUE TITLE
Duration should not be tied to SerializationFeature.WRITE_DATES_AS_TIMESTAMPS

### ISSUE THREAD

**Issue by shollander** [FasterXML/jackson-datatype-joda#31]
Based on issue https://github.com/FasterXML/jackson-datatype-joda/issues/24 Durations are now serialized in ISO-8601 format when SerializationFeature.WRITE_DATES_AS_TIMESTAMPS is disabled.  I don't believe that this behavior is correct. A Duration does not represent a Date, and should not be tied to WRITE_**DATES**__AS_TIMESTAMPS.  This also makes it impossible to provide a date formatter for writing dates, while writing durations as milliseconds.

**Comment by cowtowncoder** [comment]
I think this was implemented for 2.5.0 -- `DurationSerializer` definitely now uses `SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS` instead of `WRITE_DATES_AS_TIMESTAMPS`.

**Comment by cowtowncoder** [comment]
Hmmh. Odd. Same issue was fixed for Java 8 date/time, but for 2.10.
I'll reopen this; and due to timing this too has to be 2.10 only.

Actually I'll create a new issue as this has been included for 2.5 (rightly or wrongly)

**Comment by cowtowncoder** [comment]
@ewirch Actually I am even more confused now: as far as I can see, handling in Joda should use `WRITE_DURATIONS_AS_TIMESTAMPS`. And `JSR310FormattedSerializerBase` is not part of Joda datatype module but Java 8 date/time. So maybe you are thinking of that?
