### ISSUE TITLE
OSGi joda import does not allow joda upgrade

### ISSUE THREAD

**Issue by rgilles** [FasterXML/jackson-datatype-joda#34]
Hi,
We are using a more uptodate version of joda time. And we love to use jackson!
But the current `Import-Package` header of your `jackson-datatype-joda` bundle prevent us to upgrade.
```
Import-Package: ...
 ...
 ...,org.joda.time;version=
 "[2.1.0,2.2)",org.joda.time.format;version="[2.1.0,2.2)"
```
As you can see your restriction is strong you only support the current minor version: 2.1 and related micros.
At this point of time the latest release from joda time is the 2.3.
Maybe, an option could be to relax your upper bound like this:
```
Import-Package: ...
 ...
 ...,org.joda.time;version=
 "[2.1.0,3)",org.joda.time.format;version="[2.1.0,3)"
```

What do you think?

Thanks,

Romain.

**Comment by cowtowncoder** [comment]
Since OSGi ought to be handled now, #49 is the part regarding timezone dependency of the test.
