### ISSUE TITLE
Can't use LocalTime, LocalDate & LocalDateTime  as Key type for a Map

### ISSUE THREAD

**Issue by guidomedina** [FasterXML/jackson-datatype-joda#45]
Can't use LocalTime, LocalDate & LocalDateTime  as Key type for a Map which apparently is fixed by #41

**Comment by reka18** [comment]
This appears to be happening again. Attempting to deserialize an Map with LocalDate as keys throws a Expected Object but found String exception.

**Comment by cowtowncoder** [comment]
@reka18 If there is a problem, could you please file a new issue with version information (ideally tested against 2.11.3), and reproduction?
