### ISSUE TITLE
Calling JodaDateSerializerBase#isEmpty results in a StackOverflowError

### ISSUE THREAD

**Issue by clamothe** [FasterXML/jackson-datatype-joda#51]
`JodaDateSerializerBase#isEmpty(T value)` calls `JsonSerializer#isEmpty(null, value)` which calls `#isEmpty(value)` again, resulting in a StackOverflowError.

jackson-databind calls isEmpty when serializing various values if the object mapper is configured with `mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);`.

For example, the serialization of a bean with a non-null field value results in a JsonMappingException wrapping the StackOverflowError.

**Comment by cowtowncoder** [comment]
Ah, good catch, thanks!
