### ISSUE TITLE
Support timezone configuration for Interval deserializer.

### ISSUE THREAD

**Issue by gordchen** [FasterXML/jackson-datatype-joda#58]
Can you support timezone configuration for the interval deserializer?
The default timezone may be not always the best choice when the interval is constructed from the milliseconds, the UTC is prefered in some cases.

**Comment by cowtowncoder** [comment]
If that is useful and Joda handles it, may be possible. The main challenge is usually backwards compatibility, related to both handling of defaults (information missing), and in actual serialization format used. Contributions always welcome.

**Comment by islanderman** [comment]
To @cowtowncoder 's point, some of the default timezone in deserializers are handled different than joda's ``DateTimeZone.getDefault()``.  See below for more information.

Here's a list of datatypes that might or might not require change to support Java's ``TimeZone`` from ``DeserializationContext``.  

Deserializer | Current Default ``DateTimeZone`` 
------------------- | ---------------- 
``DateMidnightDeserializer`` | ``DateTimeZone.getDefault()``
``DateTimeDeserializer`` | ``DateTimeZone.UTC`` 
``DateTimeZoneDeserializer`` | N/A
``DurationDeserializer`` | N/A
``InstantDeserializer`` | N/A
``IntervalDeserializer`` | ``DateTimeZone.getDefault()``
``LocalDateDeserializer`` | ``DateTimeZone.getDefault()``
``LocalDateTimeDeserializer`` | ``DateTimeZone.UTC`` 
``LocalTimeDeserializer`` | ``DateTimeZone.UTC`` (``START_ARRAY``) or ``DateTimeZone.getDefault()`` (``VALUE_NUMBER_INT``)
``MonthDayDeserializer`` | ``DateTimeZone.getDefault()``
``PeriodDeserializer`` |  ``DateTimeZone.getDefault()``
``YearMonthDeserializer``| ``DateTimeZone.UTC``

**Comment by cowtowncoder** [comment]
Implemented so that if `timezone` is specified via `@JsonFormat`, it will be set as the timezone of resulting `Interval` object; that is, as the timezone of start and end times.
