### ISSUE TITLE
Deserializing invalid dates results in a IllegalArgumentException while I was expecting a JsonMappingException

### ISSUE THREAD

**Issue by ralphvanetten** [FasterXML/jackson-datatype-joda#59]
When I deserialze an invalid date an IllegalArgumentException is thrown.
I would have expected this exception to be wrapped in a Jackson exception with the field name and other information available.

I made sure the `SerializationFeature.WRAP_EXCEPTIONS` is enabled.

**Comment by cowtowncoder** [comment]
That sounds wrong, but I think a unit test (or stack trace) would be needed here. There are many different code paths to invoke deserialization, and most do handle wrapping of exceptions.
Also would be good to know the version, for verification purposes.

**Comment by cowtowncoder** [comment]
Can not reproduce, can't find any instances by Joda module itself, so closing.

**Comment by ralphvanetten** [comment]
Sorry for not responding sooner. I've tried it again and it indeed works as expected. I can only guess the problem occurred with an really old version.

**Comment by cowtowncoder** [comment]
@ralphvanetten Thank you for checking it now: better late than never! :)
