### ISSUE TITLE
Please add a LICENSE file to the project

### ISSUE THREAD

**Issue by mprentic-harris** [FasterXML/jackson-datatype-joda#61]
Or at least a license section to the README.md. Thank you.

**Comment by cowtowncoder** [comment]
I am bit torn here; I understand that visibility is useful, but license is defined in couple of places already.
Project Wiki mentions it; `src/main/resources/META-INFO` contains actual license (needs to be there to be built in jar by Maven). Pom.xml has it but only transitively (via parent pom).
And finally the main portal project (https://github.com/FasterXML/jackson) mentions that all components are Apache licensed.

But perhaps it makes sense to either add a copy of LICENSE, or mention on main README, as you suggest.

**Comment by mprentic-harris** [comment]
Just a mention of the license type in the README would be helpful. I was in the midst of doing a license check/update of all of our libraries and this was the only library on Github that we use which did not have a LICENSE file or entry in the README.

**Comment by mprentic-harris** [comment]
Thanks!
