### ISSUE TITLE
(2.8?) Apply `withOffsetParsed()` on formats by default

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-datatype-joda#75]
(note: spun from #74)

Looks like it would make sense to call `withOffsetParsed()` method on date formatters, by default, instead of having to add it depending on settings, unless there are downsides to this.
Hopefully our unit test suite can give some guidance as to any potential issues. Also obviously need to verify what Joda javadocs say about this method.

**Comment by fabianbuch** [comment]
Sounds good to me. The module jackson-datatype-jsr310 also always parses offset for OffsetDateTime and ZonedDateTime.

I agree that a general Formatter change should be tested more thoroughly. Personally I think only UTC Dates should be formatted as such and all other zones with their respective offsets. Automatic conversion to UTC could be handled by a serialization feature similar to the deserialization feature "ADJUST_DATES_TO_CONTEXT_TIME_ZONE".

**Comment by cowtowncoder** [comment]
Sigh. Trying to set as default does not quite work, as it looks like setting gets overridden. There was also an initial problem with `null` time zone (when setting `withOffsetParsed()`, otherwise set default `TimeZone` is nulled). But at this point I am not fully sure how this could or should be done, so at this point in 2.7.0 release cycle I am not going to try to change the handling.

**Comment by fred01** [comment]
Hi!
I'm very hungry for this feature! Because it's not very easy configure DateTimeSerializer in Spring Boot environment. Current default behavior seems very strange for me - why my date with some tz (i.e. +03) showed in UTC? Why UTC? Why not PRC for example? UTC have same sense for me as Shanghai - i mean no any sense.

**Comment by cowtowncoder** [comment]
@fred01 Perhaps you can come up with a PR (Pull Request) for this? This is how Open Source works.

**Comment by cowtowncoder** [comment]
It looks like `JacksonJodaDateFormat` does this already. But I am not sure if that is tested, or, if not, what'd be a good test case. Or whether issue I filed was meant to apply to formatters on output side.

So basically I don't quite know/remember what exactly should be addressed.

Given this, I will close this issue and hope that if anyone wants to proceed here they would at least provide a test case to show expected behavior; ideally stand-alone unit test.
