### ISSUE TITLE
Joda != JodaTime

### ISSUE THREAD

**Issue by pedrocborges2** [FasterXML/jackson-datatype-joda#79]
You might consider renaming this to jackson-datatype-jodaTIME since it does not support the full joda stack, joda-money for example.

**Comment by cowtowncoder** [comment]
Hmmh. Interesting point. I will have to think about this.

I agree in that ideally name would be more specific. It may be too late to change that it this point, at least wrt. Maven artifact id, due to widespread usage. Repo name could be changed more easily, not sure how valuable that would be.

**Comment by pedrocborges2** [comment]
Might be easier to extend the functionality to cover joda-money then. It is
quite trivial. There are 3 data types as far as I can remember Money,
BigMoney and CurrencyUnit.
The thing is there is no out of the box solution that covers joda-money
Jackson serialization that I know of so I reckon it would be a nice
improvement.

All the best
Pedro

**Comment by cowtowncoder** [comment]
@pedrocborges2 I think that if someone contributed `jackson-datatype-joda-money` module, I would help change this to be a multi-module maven project. While artifact name of existing module would need to remain as-is, other components could have better names.

**Comment by ingwarsw** [comment]
Not easier to just add here that 3 types?

If yes I could create PR with them..

**Comment by cowtowncoder** [comment]
@ingwarsw that could be easier, but not necessarily the right thing to do from modeling perspective: if Joda money is a separate library, it should be handled separately. 

But I would recommend raising up this at mailing list, if it is something of interest: if user community feels direct addition makes sense (with additional dependency that it entails), I don't have strong objections. But I also don't want to do that if there isn't real need.

**Comment by ingwarsw** [comment]
@cowtowncoder Mayby your rigth with separated library..

We are writing (copy/pasting between projects) at least encoders for 2 types.. Money and Currency Unit.. I suppose third would be usefull also..

**Comment by eshepelyuk** [comment]
Any news about `joda-money` support ?

**Comment by cowtowncoder** [comment]
@eshepelyuk I am not aware of anyone working on that, although there is

https://github.com/zalando/jackson-datatype-money

**Comment by eshepelyuk** [comment]
@cowtowncoder Thanks for the reference.
