### ISSUE TITLE
Error in ObjectMapperConfig example in wiki

### ISSUE THREAD

**Issue by mnuessler** [FasterXML/jackson-datatype-joda#80]
There is an [example in the wiki how you can configure the pre-defined object mappers by using a ObjectMapperConfig](https://github.com/jayway/rest-assured/wiki/Usage#configuration), but it is slightly broken. Should be:

```java
RestAssured.config = RestAssuredConfig.config().objectMapperConfig(new ObjectMapperConfig().gsonObjectMapperFactory(
		new GsonObjectMapperFactory() {
			public Gson create(Class cls, String charset) {
				return new GsonBuilder().setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES).create();
			}
		}
));
```

**Comment by cowtowncoder** [comment]
I think you may have reported this in wrong issue tracker?
