### ISSUE TITLE
JacksonJodaDateFormat, JacksonJodaFormatBase, JacksonJodaPeriodFormat needs some constructor Refactoring

### ISSUE THREAD

**Issue by joxerTMD** [FasterXML/jackson-datatype-joda#85]
In order to implement https://github.com/FasterXML/jackson-annotations/issues/95 for Joda module i suggest to add new constructor for these classes that accepts the state of formatter. We need this because the current possibility to add new factory methods is limited by constructor's signature. i.e We can't now have two factory methods of formatter like these: JacksonJodaDateFormat.withSomething(Boolean property).

**Comment by joxerTMD** [comment]
As soon as it's done we can easily implement  https://github.com/FasterXML/jackson-annotations/issues/95 like this  https://github.com/joxerTMD/jackson-datatype-joda/pull/1

**Comment by cowtowncoder** [comment]
Sounds reasonable. One thing I need at this point (unless it's already done -- apologies if so) is the Contributor License Agreement, from here:

https://github.com/FasterXML/jackson-legal/blob/master/contributor-agreement.pdf

which we need to get just once and is good for all Jackson projects.
Easiest way is usually to print it, fill & sign, scan and email to `info` at fasterxml dot com.

Looking forward to merging these patches, thank you in advance!

**Comment by joxerTMD** [comment]
the link above returns 404 error for me :(

**Comment by cowtowncoder** [comment]
@joschi ah sorry, wrong link. Will update.

**Comment by joxerTMD** [comment]
Done. CLA is signed and sent
